# This file was generated by GoReleaser. DO NOT EDIT.
class Gotham < Formula
  desc "An awesome static site generator based on Hugo."
  homepage "https://GothamHQ.com"
  version "0.3.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gothamhq/gotham/releases/download/v0.3.0/gotham-v0.3.0-macos-amd64.tar.gz"
    sha256 "dd203f58f6d0ce6ece70fa6d5c8db66c31fbc9acd4f20d834d76edcf21afe02f"
  elsif OS.linux?
  end
  
  depends_on "go"

  def install
    bin.install "gotham"
  end

  test do
    site = testpath/"hops-yeast-malt-water"
    system "#{bin}/gotham", "new", "site", site
    assert_predicate testpath/"#{site}/config.toml", :exist?
  end
end
