# This file was generated by GoReleaser. DO NOT EDIT.
class Gotham < Formula
  desc "An awesome static site generator based on Hugo."
  homepage "https://GothamHQ.com"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gothamhq/gotham/releases/download/v0.2.0/gotham-v0.2.0-macos-amd64.tar.gz"
    sha256 "a240216f92966e565422f8c8a4a272cd0a69248e3d8ac944b874c702c8fa30a6"
  elsif OS.linux?
  end
  
  depends_on "go"

  def install
    bin.install "gotham"
  end

  test do
    site = testpath/"hops-yeast-malt-water"
    system "#{bin}/gotham", "new", "site", site
    assert_predicate testpath/"#{site}/config.toml", :exist?
  end
end
