# This file was generated by GoReleaser. DO NOT EDIT.
class Gotham < Formula
  desc "An awesome static site generator based on Hugo."
  homepage "https://GothamHQ.com"
  version "0.7.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gothamhq/gotham/releases/download/v0.7.0/gotham-v0.7.0-macos-amd64.tar.gz"
    sha256 "023659c14fe70275726f1435ae0a0f7a37f79d288c125a43f5e5ad65747410f4"
  elsif OS.linux?
  end
  
  depends_on "go"

  def install
    bin.install "gotham"
  end

  test do
    site = testpath/"hops-yeast-malt-water"
    system "#{bin}/gotham", "new", "site", site
    assert_predicate testpath/"#{site}/config.toml", :exist?
  end
end
